import { Geist, Geist_Mono,Jersey_10,Jersey_10} from "next/font/google";
import "./globals.css";
import {Providers} from './lib/Providers'
import { Variable } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const jersey_10 = Jersey_10({subsets:["latin"],weight:'400'})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={jersey_10.className}
      >
        <Providers >
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
